version: '2'
services:
    oniryxhackathon-app:
        image: oniryxhackathon
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://oniryxhackathon-mysql:3306/oniryxhackathon?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    oniryxhackathon-mysql:
        extends:
            file: mysql.yml
            service: oniryxhackathon-mysql
